package dialogos;

import bd.BaseDatos;
import bd.Conexion;
import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;

import clases.Provider;

/**
 * FECHA ==> 2019-07-12.
 * Ventana para agregar un nuevo proveedor al negocio.
 * @author Luis Alejandro Gómez C.
 * @version 1.0.1.
 */
public class DialogNewProvider extends javax.swing.JDialog 
{
    /**
     * Proveedor que se desea agregar al negocio.
     */
    private Provider  provider;
    
    /**
     * Ventana donde se ingresaran los datos necesarios para registrar
     * un nuevo proveedor de surtido en el negocio.
     * @param parent Interfaz principal del sistema
     * @param modal para esta interfaz debe ser "true".
     * @param 1=> crear provider, 2=> editar un provider.
     */
    public DialogNewProvider(java.awt.Frame parent, boolean modal,int action) 
    {
        super(parent, modal);        
        initComponents();
        
        this.setLocationRelativeTo(parent);
        if(action==1){
            this. provider = null;
            this.clearContent();
        }else if(action==2){
            this.initContentEdit();
        }
    }
    
    public void clearContent(){
        this.txtName.setText("");
        this.txtNit.setText("");    
        this.txtCellphone.setText("");
        this.txtEmail.setText("");
        this.txtDirection.setText("");
    }
    
    
    
    public void initContentEdit(){
        if(this.provider!=null){
            System.out.println("no seee");
            this.txtName.setText(provider.getName());
            this.txtNit.setText(provider.getNit());    
            this.txtCellphone.setText(provider.getCellphone());
            this.txtEmail.setText(provider.getEmail());
            this.txtDirection.setText(provider.getDirection());
        
        }else{
            System.out.println("No se pudó inicializar el Dialog");
        }
    }
    /**
     * Obtiene el proveedor que se esta registrando en esta ventana.
     * @return Proveedor creado por esta ventana.
     */
    public Provider getProveedor() 
    {
        return  provider;
    }

    /**
     * Modifica el proveedor en esta ventana, se utiliza cuando 
     * se desea modificar un proveedor ya registrado en el sistema.
     * @param proveedor Proveedor que se pintara en la ventana.
     */
    public void setProvider(Provider proveedor) 
    {
        this.provider = proveedor;
        this.initContentEdit();
    }
    
    /**
     * Hace todas las validaciones para crear proveedor en sistema.
     * @return Si es valido o no el proveedor que se intenta registrar.
     */
    public boolean checkProvider()
    {
        
        String name = this.txtName.getText();
        String nit = this.txtNit.getText().replace(" ", "");    
        String cellphone = this.txtCellphone.getText().replace(" ", "");
        String email = this.txtEmail.getText().replace(" ", "");
        String direction = this.txtDirection.getText().replace(" ", "");
        
        boolean bandera = false;        
        //Se crea un proveedor seimpre con todos los datos.
        if(!name.equals("")||!nit.equals("")||!cellphone.equals("")||!direction.equals("")||!email.equals(""))
        {
            try
            {            
                this. provider = new Provider("100",name, nit, cellphone,email,direction);                  
                bandera = true;
            }
            catch(HeadlessException e) 
            {
                JOptionPane.showMessageDialog(null,"Error, Compruebe Los Datos Ingresados");
            }  
                                            
        }
        else
            JOptionPane.showMessageDialog(null,"Debe Ingresar Todos Los Datos Para Registrar El Proveedor");
        
        return bandera;        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelContenedor = new javax.swing.JPanel();
        panelEncabezado = new javax.swing.JPanel();
        txtEncabezado = new javax.swing.JLabel();
        txtSalir = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblNit = new javax.swing.JLabel();
        txtNit = new javax.swing.JTextField();
        lblCellphone = new javax.swing.JLabel();
        txtCellphone = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtEmail = new javax.swing.JTextField();
        txtDirection = new javax.swing.JTextField();
        lblDirection = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        panelContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelEncabezado.setBackground(new java.awt.Color(36, 52, 81));

        txtEncabezado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        txtEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccion.png"))); // NOI18N
        txtEncabezado.setText("      Agregar Proveedor");

        txtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrar.png"))); // NOI18N
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSalir))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addComponent(txtSalir)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblName.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblName.setText("Nombre:");

        txtName.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        lblNit.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblNit.setText("Nit:");

        txtNit.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        lblCellphone.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblCellphone.setText("Teléfono:");

        txtCellphone.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        btnAceptar.setBackground(new java.awt.Color(20, 60, 108));
        btnAceptar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(176, 95, 95));
        btnCancelar.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtEmail.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        txtDirection.setFont(new java.awt.Font("Cambria", 0, 16)); // NOI18N

        lblDirection.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblDirection.setText("Dirección - Ciudad");

        lblEmail.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        lblEmail.setText("Correo Electronico");

        javax.swing.GroupLayout panelContenedorLayout = new javax.swing.GroupLayout(panelContenedor);
        panelContenedor.setLayout(panelContenedorLayout);
        panelContenedorLayout.setHorizontalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblName)
                    .addComponent(lblEmail)
                    .addComponent(lblDirection)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtDirection, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNit)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCellphone))))
                .addGap(0, 16, Short.MAX_VALUE))
            .addComponent(panelEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(btnCancelar)
                .addGap(78, 78, 78)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelContenedorLayout.setVerticalGroup(
            panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenedorLayout.createSequentialGroup()
                .addComponent(panelEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(lblCellphone)
                        .addGap(78, 78, 78))
                    .addGroup(panelContenedorLayout.createSequentialGroup()
                        .addComponent(lblNit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCellphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail)
                        .addGap(4, 4, 4)))
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblDirection)
                .addGap(4, 4, 4)
                .addComponent(txtDirection, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(panelContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        boolean bandera = this.checkProvider();
        //Si ingreso un proveedor correcto pasa a intentar registrarlo en la base de datos.
        if(bandera)
            this.dispose();        
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel lblCellphone;
    private javax.swing.JLabel lblDirection;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNit;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JTextField txtCellphone;
    private javax.swing.JTextField txtDirection;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JLabel txtEncabezado;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNit;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
