/**
 * Mostrará todos los insumos qu es e hayan incluido en cada Compra.
 */
package dialogos;

import clases.Purchase;
import clases.Supply;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import logicainterfaz.RenderTable;
import logicainterfaz.TableController;

/**
 *
 * @author ever
 */
public class DialogDetailPurchase extends javax.swing.JDialog {

    private final Font font1= new Font("Cambria", 0, 18);
    private Purchase purchase;
    private DefaultTableModel modelo; 
    /**
     * Creates new form DetailPurchase
     */
    public DialogDetailPurchase(java.awt.Frame parent, boolean modal,Purchase purchase) {
        super(parent, modal);
        initComponents();
        this.lblObservation.setText(purchase.getId()+"tamaño:"+purchase.getInsumos().size());
        this.setLocationRelativeTo(null);
        this.lblCreated.setText(purchase.getCreateAt()+"");
        this.lblProvider.setText(purchase.getProvider().getName());
        this.lblObservation.setText(purchase.getObservation());
        
        this.purchase=purchase;
        this.createTable(purchase.getInsumos());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelEncabezado = new javax.swing.JPanel();
        txtSalir = new javax.swing.JLabel();
        txtEncabezado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblProvider = new javax.swing.JLabel();
        lblCreated = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lblObservation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEncabezado.setBackground(new java.awt.Color(36, 52, 81));

        txtSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrar.png"))); // NOI18N
        txtSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSalirMouseClicked(evt);
            }
        });

        txtEncabezado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtEncabezado.setForeground(new java.awt.Color(255, 255, 255));
        txtEncabezado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/seleccion.png"))); // NOI18N
        txtEncabezado.setText("Detalle de La Compra");

        javax.swing.GroupLayout panelEncabezadoLayout = new javax.swing.GroupLayout(panelEncabezado);
        panelEncabezado.setLayout(panelEncabezadoLayout);
        panelEncabezadoLayout.setHorizontalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEncabezadoLayout.createSequentialGroup()
                .addComponent(txtEncabezado, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 473, Short.MAX_VALUE)
                .addComponent(txtSalir)
                .addGap(15, 15, 15))
        );
        panelEncabezadoLayout.setVerticalGroup(
            panelEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEncabezadoLayout.createSequentialGroup()
                .addComponent(txtSalir)
                .addGap(0, 21, Short.MAX_VALUE))
            .addComponent(txtEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        getContentPane().add(panelEncabezado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        lblProvider.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblProvider.setForeground(new java.awt.Color(0, 0, 153));
        lblProvider.setText("NOMBRE PROVEEDOR");

        lblCreated.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblCreated.setForeground(new java.awt.Color(0, 0, 153));
        lblCreated.setText("FECHA CREACION");

        lblObservation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblObservation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblObservation.setText("sabdhsbdhas dash dasd djsdbjas djas dasj dasdjas djasbdjasdjasbdasjdbjas dasjdjasdjasbdjasbdjasbdjasbdasjd");
        jScrollPane2.setViewportView(lblObservation);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("Proveedor");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setText("Observaciones o Comentarios:");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setText("Fecha Creación:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 12, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreated, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProvider, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 810, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSalirMouseClicked
        this.dispose();
    }//GEN-LAST:event_txtSalirMouseClicked

    
    
    
    
        /**
     * Da configuración y estilos a la Tabla y sus botones
     */
    public void initTable(){

        
        table.setDefaultRenderer(Object.class, new RenderTable());
        //Define Columnas y desabilita edicion.
        this.modelo = new DefaultTableModel(
                        new Object[][]{{"","","","","","",""}},
                        new Object[] {"Id","Nombre","Peso_Comprado","U_Medida","Categoria","Precio_Insumo"} 
                    ){
                        public boolean isCellEditable(int rowIndex, int vColIndex) {
                            return false;
                        }
                    };
        JTableHeader header = table.getTableHeader();
        header.setFont(font1);
        header.setForeground(new Color(255,255,255));
        header.setBackground(new Color(73, 93, 101 ));
    }
    
    
     /**
     * Metodo que crea y llena la Tabla.
     * @param insumos 
     */
    public void createTable(ArrayList<Supply>supplies)
    {
        //inicializa estilos de la tabla y sus botones.
        this.initTable();
        this.table.setModel(modelo);
        this.defineWidthColumnsTable();
                
        //Limpia datos viejos de la tabla
        this.clearDataFromTable();
        //Llena la Tabla con Providers del Restaurante.
        if(supplies.size()>0 && supplies!=null){
            try{
                for(int i=0;i<supplies.size();i++)
                {
                    Supply sup=supplies.get(i);
                    Object [] arreglo ={sup.getId(),sup.getName(),sup.getWeight()
                            ,sup.getCategory().getUnityMeasure(),sup.getCategory().getName(),
                            sup.getPrice_purchase()};
                    modelo.addRow(arreglo);    
                }
                table.setModel(modelo);
            }catch(Exception e){ 
                System.out.println("ERROR:pintando tabla proveedores"+e.getMessage());
            }
        }
        
       
    }
    
    
    /**
     * Hace el barrido de la información contenida en una tabla.
     * @param modeloTabla Modelo de la tabla que se desea barrer.
     */
    public void clearDataFromTable()
    {        
        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
        {
            modelo.removeRow(i);
        }            
    }
    
        /**
     * Define el ancho de las columnas de la tabla
     */
    public void defineWidthColumnsTable(){
        this.table.getColumnModel().getColumn(0).setPreferredWidth(20);
        this.table.getColumnModel().getColumn(1).setPreferredWidth(100);
        this.table.getColumnModel().getColumn(2).setPreferredWidth(90);

        //unidad de medida
        this.table.getColumnModel().getColumn(3).setPreferredWidth(50);
        //name category
        this.table.getColumnModel().getColumn(4).setPreferredWidth(90);
        this.table.getColumnModel().getColumn(5).setPreferredWidth(92);
  
       
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DialogDetailPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DialogDetailPurchase dialog = new DialogDetailPurchase(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblObservation;
    private javax.swing.JLabel lblProvider;
    private javax.swing.JPanel panelEncabezado;
    private javax.swing.JTable table;
    private javax.swing.JLabel txtEncabezado;
    private javax.swing.JLabel txtSalir;
    // End of variables declaration//GEN-END:variables
}
