
package interfaz;

import clases.Provider;
import clases.Restaurant;
import dialogos.DialogNewProvider;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import logicainterfaz.RenderTable;
import logicainterfaz.TableController;

/**
 *
 * @author ever
 */
public class PanelProveedores extends javax.swing.JPanel {


    private Restaurant restaurant;
    private TableController tableController;
    private DefaultTableModel modelo; 
    private DialogNewProvider dialogProvider;
    
                        
    private final ImageIcon incoEdit = new ImageIcon("src/img/iconEdit2.png");
    private final ImageIcon incoDelete = new ImageIcon("src/img/iconDelete2.png");
    
    private JButton edit;
    private JButton delete;
    private final Font font1= new Font("Cambria", 0, 18);
    /**
     * Creates new form PanelCompras
     */
    public PanelProveedores(String titulo,Restaurant restaurant) {
        initComponents();
        lblTitulo.setText(titulo);
        lblTitulo.setFont(font1);
        this.restaurant=restaurant;
        this.tableController=new TableController(this.restaurant);
        
        this.createTable(restaurant.getProviders());
    }
    public PanelProveedores(String titulo) {
        initComponents();
        lblTitulo.setText(titulo);
    }
    
     
    /**
     * Metodo que crea y llena la Tabla.
     * @param providers 
     */
    public void createTable(ArrayList<Provider>providers)
    {
        //inicializa estilos de la tabla y sus botones.
        this.initTable();
        //Limpia datos viejos de la tabla
        this.clearDataFromTable();
        //Llena la Tabla con Providers del Restaurante.
        if(providers.size()>0&&providers!=null){
            try{
                for(int i=0;i<providers.size();i++)
                {
                    Provider prov=providers.get(i);
                    Object [] arreglo ={prov.getId(),prov.getName(),prov.getNit()
                            ,prov.getCellphone(),prov.getEmail(),prov.getDirection(),edit,delete};
                    modelo.addRow(arreglo);    
                }
                table.setModel(modelo);
            }catch(Exception e){ 
                System.out.println("ERROR:pintando tabla proveedores"+e.getMessage());
            }
        }
       
    }
    
    
    /**
     * Da configuración y estilos a la Tabla y sus botones
     */
    public void initTable(){
        
        edit= new JButton("Editar");
        edit.setIcon(incoEdit);
        edit.setName("btnEdit");
        edit.setBackground(new Color(37, 122, 218 ));
        edit.setForeground(new Color(255,255,255));
                   
        
        
        delete= new JButton("Borrar");
        delete.setIcon(incoDelete);
        delete.setName("btnDelete");
        delete.setBackground(new Color(217, 99, 126 ));
        delete.setForeground(new Color(255,255,255));
        
        
        table.setDefaultRenderer(Object.class, new RenderTable());
        //Define Columnas y desabilita edicion.
        this.modelo = new DefaultTableModel(
                        new Object[][]{{"","","","","","",""}},
                        new Object[] {"ID","Nombre","Nit","Telefono","Email","Dirección","M","E"} 
                    ){
                        public boolean isCellEditable(int rowIndex, int vColIndex) {
                            return false;
                        }
                    };
        JTableHeader header = table.getTableHeader();
        header.setFont(font1);
        header.setForeground(new Color(255,255,255));
        header.setBackground(new Color(73, 93, 101 ));
    }
    
    /**
     * Hace el barrido de la información contenida en una tabla.
     * @param modeloTabla Modelo de la tabla que se desea barrer.
     */
    public void clearDataFromTable()
    {        
        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
        {
            modelo.removeRow(i);
        }            
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        scrollTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 21)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("TITULO DE LA TABLA");

        scrollTable.setBackground(new java.awt.Color(255, 255, 255));
        scrollTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scrollTableMouseClicked(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        scrollTable.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(325, 325, 325))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void scrollTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scrollTableMouseClicked
        
        
    }//GEN-LAST:event_scrollTableMouseClicked

    
    /**
     * Evento cuando se clickea la Table del Panel
     * @param evt 
     */
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int col=table.getColumnModel().getColumnIndexAtX(evt.getX());
        int row=evt.getY()/table.getRowHeight();
        
        //Verifica que lo que clikeo fué un boton
        if(row < table.getRowCount()  && row >= 0 && col < table.getColumnCount()
                && col >= 0){
            Object value=table.getValueAt(row, col);
            if(value instanceof JButton){
                ((JButton)value).doClick();
                JButton btn= (JButton)value;
                
                if(btn.getName().equals("btnEdit")){
                    this.editProvider();
                }else if(btn.getName().equals("btnDelete")){
                    this.deleteProvider();
                }
                System.out.println(btn.getName());
            }
//            
            
        }
    }//GEN-LAST:event_tableMouseClicked

    
    
    /**
     * Se llama al dar click en la tabla, boton editar
     * Interacrua con la BD del Restaurante
     */
    public void editProvider(){
       
        Provider provOld = this.tableController.getProviderFromTable(this.table);
        if(provOld == null)
            JOptionPane.showMessageDialog(this, "No Se Seleccionó Ningún Proveedor");
        else
        {            
            this.dialogProvider= new  DialogNewProvider(null, true,2);
            this.dialogProvider.setProvider(provOld);
            this.dialogProvider.setVisible(true);
            //el dialogo modifica el provedor de la table y me da uno nuevo
            Provider provNew=dialogProvider.getProveedor();
            
            boolean ban = this.restaurant.getBd().getCrudProvider().updateProvider(provOld, provNew);
           
            if(ban)
            {
                JOptionPane.showMessageDialog(this, "Proveedor  Actualizado Correctamente");
                this.restaurant.updateDataBase();
                //this.paintTableProveedores();
                this.createTable(this.restaurant.getProviders());
            }
            else
            {
                JOptionPane.showMessageDialog(this, "No Se Pudo Eliminar El Proveedor De La Base De Datos");
            }          
        }  
        
        System.out.println("editProvide");
    }
    
    
    
    /**
     * Se llama al darle click a la tabla en el boton delete.
     */
    public void deleteProvider(){
        Provider prov = this.tableController.getProviderFromTable(this.table);
        if(prov == null)
            JOptionPane.showMessageDialog(this, "No Se Seleccionó Ningún Proveedor");
        else
        {            
            String name = prov.getName();
            int opc = JOptionPane.showConfirmDialog(null, "Realmente Desea Eliminar El Proveedor " + name.toUpperCase(),
                    "Eliminar Proveedor", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //0 para si || 1 para no
            if (opc == 0)
            {
                boolean ban = this.restaurant.getBd().getCrudProvider().deleteProvider(prov);
                //Si se elimino el proveedor de la base de datos.
                if(ban)
                {
                    JOptionPane.showMessageDialog(this, "Proveedor " + name.toUpperCase() + " Eliminado Correctamente");
                    this.restaurant.updateDataBase();
                    //this.paintTableProveedores();
                    this.createTable(this.restaurant.getProviders());
//                    this.pintor.paintTableProviders(this.tequilazo.getProveedores(), this.modeloListaProveedores);
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "No Se Pudo Eliminar El Proveedor De La Base De Datos");
                }
            }            
        }   
        System.out.println("deleteProvide");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JScrollPane scrollTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
