
package interfaz;

import clases.Menu;
import clases.Provider;
import clases.Restaurant;
import clases.Supply;
import dialogos.DialogNewMenu;
import dialogos.DialogNewProvider;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import logicainterfaz.RenderTable;
import logicainterfaz.TableController;

/**
 *
 * @author ever
 */
public class PanelMenus extends javax.swing.JPanel {


    private Restaurant restaurant;
    private TableController tableController;
    private DefaultTableModel modelo; 
    private DialogNewProvider dialogProvider;
    
                        
    private final ImageIcon incoEdit = new ImageIcon("src/img/iconEdit2.png");
    private final ImageIcon incoDelete = new ImageIcon("src/img/iconDelete2.png");
    
    private JButton edit;
    private JButton delete;
    private final Font font1= new Font("Cambria", 0, 18);
    /**
     * Creates new form PanelCompras
     */
    public PanelMenus(String titulo,Restaurant restaurant) {
        initComponents();
        lblTitulo.setText(titulo);
        this.restaurant=restaurant;
        this.tableController=new TableController(this.restaurant);
        
        this.createTable(null);
        this.paintListMenus(restaurant.getMenus());
    }
    public PanelMenus(String titulo) {
        initComponents();
        lblTitulo.setText(titulo);
    }
    
     
    public void paintListMenus(ArrayList<Menu> menus)
    {
        DefaultListModel listModel = new DefaultListModel();
        String aux = "";                
        int numCats = menus.size();
        this.listMenus.removeAll();
        Menu menu;

        for(int i = 0; i < numCats; i++) 
        {
            menu = menus.get(i);
            aux = menu.getId()+"-"+menu.getName();
            listModel.add(0, aux);
//            this.combSupplies.addItem(aux);
        }
        this.listMenus.setModel(listModel);
    }
    
    
    
    
    
    
    /**
     * Metodo que crea y llena la Tabla.
     * @param providers 
     */
    public void createTable(ArrayList<Supply>supplies)
    {
        //inicializa estilos de la tabla y sus botones.
        this.initTable();
        //Limpia datos viejos de la tabla
        this.clearDataFromTable();
        //Llena la Tabla con Providers del Restaurante.
        if(supplies!=null&&supplies.size()>0){
            try{
                for(int i=0;i<supplies.size();i++)
                {
                    Supply sup=supplies.get(i);
                    Object [] arreglo ={sup.getId(),sup.getName(),sup.getWeight()
                            ,sup.getCategory().getUnityMeasure(),sup.getCategory().getName()};
                    modelo.addRow(arreglo);    
                }
                table.setModel(modelo);
            }catch(Exception e){ 
                System.out.println("ERROR:pintando tabla proveedores"+e.getMessage());
            }
        }
        this.table.getColumnModel().getColumn(0).setPreferredWidth(12);
       
    }
    
    
    /**
     * Da configuración y estilos a la Tabla.
     */
    public void initTable(){
        
        table.setDefaultRenderer(Object.class, new RenderTable());
        //Define Columnas y desabilita edicion.
        this.modelo = new DefaultTableModel(
                        new Object[][]{{"","","","","","",""}},
                        new Object[] {"ID","Nombre","Peso","U_Medidad","Categoria"} 
                    ){
                        public boolean isCellEditable(int rowIndex, int vColIndex) {
                            return false;
                        }
                    };
        JTableHeader header = table.getTableHeader();
        header.setFont(font1);
        header.setForeground(new Color(255,255,255));
        header.setBackground(new Color(73, 93, 101 ));
        this.table.setModel(modelo);
    }
    
    /**
     * Hace el barrido de la información contenida en una tabla.
     * @param modeloTabla Modelo de la tabla que se desea barrer.
     */
    public void clearDataFromTable()
    {        
        int a =modelo.getRowCount()-1;
        for(int i=a; i>=0; i--)
        {
            modelo.removeRow(i);
        }            
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listMenus = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnEditarMenu = new javax.swing.JButton();
        btnEliminarMenu = new javax.swing.JButton();
        btnAgregarMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNameMenu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setText("LISTA DE MENUS RESTAURANTE ");

        listMenus.setBackground(new java.awt.Color(252, 248, 232));
        listMenus.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        listMenus.setForeground(new java.awt.Color(102, 102, 102));
        listMenus.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listMenus.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listMenus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listMenusMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listMenus);

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 204));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(table);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Lista de Ingredientes");

        btnEditarMenu.setBackground(new java.awt.Color(19, 115, 184));
        btnEditarMenu.setForeground(new java.awt.Color(102, 153, 255));
        btnEditarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEditar.png"))); // NOI18N
        btnEditarMenu.setText("Editar");

        btnEliminarMenu.setBackground(new java.awt.Color(222, 102, 123));
        btnEliminarMenu.setForeground(new java.awt.Color(102, 0, 0));
        btnEliminarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoEliminar.png"))); // NOI18N
        btnEliminarMenu.setText("Eliminar");
        btnEliminarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMenuMouseClicked(evt);
            }
        });

        btnAgregarMenu.setBackground(new java.awt.Color(113, 218, 168));
        btnAgregarMenu.setForeground(new java.awt.Color(0, 51, 51));
        btnAgregarMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnAgregarMenu.setText("Nuevo Menú");
        btnAgregarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMenuMouseClicked(evt);
            }
        });
        btnAgregarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Mis Menús");

        lblNameMenu.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblNameMenu.setForeground(new java.awt.Color(102, 102, 102));
        lblNameMenu.setText("Menú");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNameMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(btnEditarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminarMenu)
                        .addGap(85, 85, 85)
                        .addComponent(btnAgregarMenu)
                        .addGap(85, 85, 85))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(222, 222, 222))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblNameMenu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listMenusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listMenusMouseClicked
        System.out.println(  this.listMenus.getSelectedValue());
        Menu men=this.tableController.getMenuFromList(listMenus);
        this.lblNameMenu.setText(men.getName());
        this.createTable(men.getSupplies());
    }//GEN-LAST:event_listMenusMouseClicked

    private void btnAgregarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarMenuActionPerformed

    private void btnAgregarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMenuMouseClicked
        DialogNewMenu newMenu= new DialogNewMenu( null, true, restaurant);
        newMenu.setVisible(true);
        Menu menu=newMenu.getMenu();
        boolean bandera=this.restaurant.addMenu(menu);
        this.paintListMenus(this.restaurant.getMenus());
        
        System.out.println("La Bandera :::::"+bandera);
    }//GEN-LAST:event_btnAgregarMenuMouseClicked

    /**
     * 
     * @param evt 
     */
    private void btnEliminarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMenuMouseClicked
        Menu men=this.tableController.getMenuFromList(listMenus);
        if(men == null)
            JOptionPane.showMessageDialog(this, "Debe Selecccionar un Menú de La Lista");
        else
        {            
            int opc = JOptionPane.showConfirmDialog(null, "Realmente Desea Eliminar El Insumo: "+men.getName().toUpperCase(),
                    "Eliminar Menú"+men.getName().toUpperCase(), JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            //0 para si || 1 para no
            if (opc == 0)
            { 
                boolean ban=this.restaurant.deleteMenu(men);

                this.restaurant.updateDataBase();
                this.paintListMenus(this.restaurant.getMenus());
                this.createTable(null);
            } 
        }
    }//GEN-LAST:event_btnEliminarMenuMouseClicked

    
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarMenu;
    private javax.swing.JButton btnEditarMenu;
    private javax.swing.JButton btnEliminarMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNameMenu;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JList<String> listMenus;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
