
package interfaz;

import clases.Category;
import clases.Provider;
import clases.Purchase;
import clases.Restaurant;
import clases.Supply;
import dialogos.DialogNewProvider;
import dialogos.DialogNewPurchase;
import dialogos.DialogSupply;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author ever
 */
public class Principal extends javax.swing.JFrame {

    private final Restaurant restaurante;
    //tablas con listados
    private PanelCompras panelCompras;
    private PanelProveedores panelProveedores;
    private PanelInsumos panelInsumos;
    private PanelMenus panelMenus;
    
    
    
    private DialogNewProvider dialogProvider;
    private  int[] colorVerde={25,139,87};
    /**
     * Creates new form Principal
     * @param restaurante
     */
    public Principal(Restaurant restaurant) {
        initComponents();
        this.restaurante=restaurant;
        this.setLocationRelativeTo(null);
        //Todos los Paneles que va a pintar.    
        this.panelProveedores= new PanelProveedores("Lista De Proveedores",restaurante);
        this.panelInsumos= new PanelInsumos("Lista De Insumos",restaurante);
        this.panelMenus= new  PanelMenus("Lista de Los Menus Del Restaurante");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHead = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        minim = new javax.swing.JLabel();
        salir = new javax.swing.JLabel();
        txtFecha = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        panelNav = new javax.swing.JPanel();
        btnListaSalidas = new javax.swing.JButton();
        btnListaInsumos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnListaCompras = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnListaProveedores = new javax.swing.JButton();
        btnCrearCompras = new javax.swing.JButton();
        btnCrearSalida = new javax.swing.JButton();
        btnCrearProveedor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnAjustes = new javax.swing.JButton();
        btnListaVentas = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btnCreateSupply = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnMenus = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelHead.setBackground(new java.awt.Color(7, 102, 131));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Restaurante Sabores De Antaño ");

        minim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoMinimizar.png"))); // NOI18N
        minim.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimMouseClicked(evt);
            }
        });

        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrar.png"))); // NOI18N
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });

        txtFecha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/calendario.png"))); // NOI18N
        txtFecha.setText("2019");

        txtNombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/usuario.png"))); // NOI18N
        txtNombre.setText("Jorge Miguel Rincon Herrera");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/inicio.png"))); // NOI18N
        jLabel2.setText("Sección");

        javax.swing.GroupLayout panelHeadLayout = new javax.swing.GroupLayout(panelHead);
        panelHead.setLayout(panelHeadLayout);
        panelHeadLayout.setHorizontalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minim)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salir)
                        .addGap(6, 6, 6))
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(txtNombre)
                        .addGap(72, 72, 72))))
        );
        panelHeadLayout.setVerticalGroup(
            panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHeadLayout.createSequentialGroup()
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHeadLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(minim)
                            .addComponent(salir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHeadLayout.createSequentialGroup()
                        .addContainerGap(40, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)))
                .addGroup(panelHeadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFecha)
                    .addComponent(txtNombre)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        getContentPane().add(panelHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 860, 160));

        panelNav.setBackground(new java.awt.Color(50, 113, 166));
        panelNav.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnListaSalidas.setBackground(new java.awt.Color(50, 113, 166));
        btnListaSalidas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnListaSalidas.setForeground(new java.awt.Color(255, 255, 255));
        btnListaSalidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/inconMenu.png"))); // NOI18N
        btnListaSalidas.setText("             Salidas");
        btnListaSalidas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnListaSalidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaSalidas.setFocusable(false);
        btnListaSalidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaSalidasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaSalidasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaSalidasMouseExited(evt);
            }
        });
        btnListaSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaSalidasActionPerformed(evt);
            }
        });
        panelNav.add(btnListaSalidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 170, 40));

        btnListaInsumos.setBackground(new java.awt.Color(50, 113, 166));
        btnListaInsumos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnListaInsumos.setForeground(new java.awt.Color(255, 255, 255));
        btnListaInsumos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alimentos.png"))); // NOI18N
        btnListaInsumos.setText("        Insumos");
        btnListaInsumos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnListaInsumos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaInsumos.setFocusable(false);
        btnListaInsumos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaInsumosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaInsumosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaInsumosMouseExited(evt);
            }
        });
        btnListaInsumos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaInsumosActionPerformed(evt);
            }
        });
        panelNav.add(btnListaInsumos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 170, -1));

        btnSalir.setBackground(new java.awt.Color(204, 123, 133));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        btnSalir.setText("             Salir");
        btnSalir.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setFocusable(false);
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalirMouseExited(evt);
            }
        });
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelNav.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 170, 30));

        btnListaCompras.setBackground(new java.awt.Color(50, 113, 166));
        btnListaCompras.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnListaCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnListaCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buy.png"))); // NOI18N
        btnListaCompras.setText("   Mis Compras");
        btnListaCompras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnListaCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaCompras.setFocusable(false);
        btnListaCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaComprasMouseExited(evt);
            }
        });
        btnListaCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaComprasActionPerformed(evt);
            }
        });
        panelNav.add(btnListaCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 170, 40));

        jButton5.setBackground(new java.awt.Color(235, 141, 141));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        jButton5.setText("Salir");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelNav.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 697, 169, -1));

        btnListaProveedores.setBackground(new java.awt.Color(50, 113, 166));
        btnListaProveedores.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnListaProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnListaProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proveedores.png"))); // NOI18N
        btnListaProveedores.setText("   Proveedores");
        btnListaProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnListaProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaProveedores.setFocusable(false);
        btnListaProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListaProveedoresMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaProveedoresMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaProveedoresMouseExited(evt);
            }
        });
        btnListaProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaProveedoresActionPerformed(evt);
            }
        });
        panelNav.add(btnListaProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 169, 30));

        btnCrearCompras.setBackground(new java.awt.Color(50, 113, 166));
        btnCrearCompras.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCrearCompras.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnCrearCompras.setText("Crear Compra");
        btnCrearCompras.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrearCompras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearCompras.setFocusPainted(false);
        btnCrearCompras.setFocusable(false);
        btnCrearCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearComprasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearComprasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearComprasMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnCrearComprasMouseReleased(evt);
            }
        });
        btnCrearCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearComprasActionPerformed(evt);
            }
        });
        panelNav.add(btnCrearCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 164, 168, 40));

        btnCrearSalida.setBackground(new java.awt.Color(50, 113, 166));
        btnCrearSalida.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCrearSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnCrearSalida.setText("  Crear Salida");
        btnCrearSalida.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrearSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearSalida.setFocusable(false);
        btnCrearSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearSalidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearSalidaMouseExited(evt);
            }
        });
        btnCrearSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearSalidaActionPerformed(evt);
            }
        });
        panelNav.add(btnCrearSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 168, 40));

        btnCrearProveedor.setBackground(new java.awt.Color(50, 113, 166));
        btnCrearProveedor.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCrearProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnCrearProveedor.setText("      Proveedor");
        btnCrearProveedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCrearProveedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCrearProveedor.setFocusable(false);
        btnCrearProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearProveedorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearProveedorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearProveedorMouseExited(evt);
            }
        });
        btnCrearProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProveedorActionPerformed(evt);
            }
        });
        panelNav.add(btnCrearProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 168, 40));

        jLabel4.setBackground(new java.awt.Color(169, 60, 60));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/letters.png"))); // NOI18N
        panelNav.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 157));

        btnAjustes.setBackground(new java.awt.Color(50, 113, 166));
        btnAjustes.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAjustes.setForeground(new java.awt.Color(255, 255, 255));
        btnAjustes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoAjustes.png"))); // NOI18N
        btnAjustes.setText("        Ajustes");
        btnAjustes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAjustes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAjustes.setFocusable(false);
        btnAjustes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAjustesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAjustesMouseExited(evt);
            }
        });
        btnAjustes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjustesActionPerformed(evt);
            }
        });
        panelNav.add(btnAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 170, 30));

        btnListaVentas.setBackground(new java.awt.Color(50, 113, 166));
        btnListaVentas.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnListaVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnListaVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        btnListaVentas.setText("       Mis Ventas");
        btnListaVentas.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnListaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnListaVentas.setFocusable(false);
        btnListaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnListaVentasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnListaVentasMouseExited(evt);
            }
        });
        btnListaVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaVentasActionPerformed(evt);
            }
        });
        panelNav.add(btnListaVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 170, 40));
        panelNav.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 170, -1));

        btnCreateSupply.setBackground(new java.awt.Color(50, 113, 166));
        btnCreateSupply.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCreateSupply.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateSupply.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar.png"))); // NOI18N
        btnCreateSupply.setText("            Insumo");
        btnCreateSupply.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCreateSupply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCreateSupply.setFocusable(false);
        btnCreateSupply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateSupplyMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCreateSupplyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCreateSupplyMouseExited(evt);
            }
        });
        btnCreateSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSupplyActionPerformed(evt);
            }
        });
        panelNav.add(btnCreateSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 168, 40));
        panelNav.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 170, -1));

        btnMenus.setBackground(new java.awt.Color(50, 113, 166));
        btnMenus.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnMenus.setForeground(new java.awt.Color(255, 255, 255));
        btnMenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menus.png"))); // NOI18N
        btnMenus.setText("                Menus");
        btnMenus.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnMenus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenus.setFocusable(false);
        btnMenus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMenusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMenusMouseExited(evt);
            }
        });
        btnMenus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenusActionPerformed(evt);
            }
        });
        panelNav.add(btnMenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 170, 40));

        getContentPane().add(panelNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 620));

        panelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        panelPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
        );

        getContentPane().add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 860, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaComprasActionPerformed
      
//        panelCompras.setVisible(true);
        
    }//GEN-LAST:event_btnListaComprasActionPerformed

    private void btnListaSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaSalidasActionPerformed
        panelCompras= new PanelCompras("Ejemplo2");
        panelCompras.setSize(860, 460);
//        panelCompras.setLocation(5, 5);
        panelPrincipal.removeAll();
        panelPrincipal.add(panelCompras);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnListaSalidasActionPerformed

    private void minimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimMouseClicked

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        int a=JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_salirMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int a=JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnCrearComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearComprasActionPerformed

    private void btnCrearSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearSalidaActionPerformed

    private void btnCrearProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearProveedorActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnListaInsumosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaInsumosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaInsumosActionPerformed

    private void btnListaProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaProveedoresActionPerformed
        this.panelProveedores= new PanelProveedores("Lista de Los Proveedores", restaurante);
        this.panelProveedores.setSize(860, 460);
//        panelCompras.setLocation(5, 5);
        panelPrincipal.removeAll();
        panelPrincipal.add(panelProveedores);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnListaProveedoresActionPerformed

    private void btnAjustesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjustesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjustesActionPerformed

    private void btnListaVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaVentasActionPerformed

    private void btnCrearComprasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearComprasMouseReleased
        this.btnCrearCompras.setBorderPainted(true);
    }//GEN-LAST:event_btnCrearComprasMouseReleased

    private void btnCrearComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearComprasMouseEntered

        this.btnCrearCompras.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnCrearComprasMouseEntered

    private void btnCrearComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearComprasMouseExited
        this.btnCrearCompras.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnCrearComprasMouseExited

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
        int a=JOptionPane.showConfirmDialog(null, "Desea Salir del Sistema?", "Confirmar salida", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(a==0)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnCrearSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearSalidaMouseEntered
        this.btnCrearSalida.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnCrearSalidaMouseEntered

    private void btnCrearProveedorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProveedorMouseEntered
        this.btnCrearProveedor.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnCrearProveedorMouseEntered

    private void btnListaComprasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaComprasMouseEntered
        this.btnListaCompras.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnListaComprasMouseEntered

    private void btnListaSalidasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalidasMouseEntered
        this.btnListaSalidas.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnListaSalidasMouseEntered

    private void btnListaInsumosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaInsumosMouseEntered
        this.btnListaInsumos.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnListaInsumosMouseEntered

    private void btnListaProveedoresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaProveedoresMouseEntered
        this.btnListaProveedores.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnListaProveedoresMouseEntered

    private void btnListaVentasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaVentasMouseEntered
        this.btnListaVentas.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnListaVentasMouseEntered

    private void btnCrearSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearSalidaMouseExited
        this.btnCrearSalida.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnCrearSalidaMouseExited

    private void btnCrearProveedorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProveedorMouseExited
        this.btnCrearProveedor.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnCrearProveedorMouseExited

    private void btnListaComprasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaComprasMouseExited
        this.btnListaCompras.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnListaComprasMouseExited

    private void btnListaSalidasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalidasMouseExited
        this.btnListaSalidas.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnListaSalidasMouseExited

    private void btnListaInsumosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaInsumosMouseExited
        this.btnListaInsumos.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnListaInsumosMouseExited

    private void btnListaProveedoresMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaProveedoresMouseExited
        this.btnListaProveedores.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnListaProveedoresMouseExited

    private void btnListaVentasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaVentasMouseExited
        this.btnListaVentas.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnListaVentasMouseExited

    private void btnAjustesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseEntered
        this.btnAjustes.setBackground(new Color(48, 61, 66));
    }//GEN-LAST:event_btnAjustesMouseEntered

    private void btnAjustesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjustesMouseExited
       this.btnAjustes.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnAjustesMouseExited

    private void btnSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseEntered
        this.btnSalir.setBackground(new Color(180, 13, 13));
    }//GEN-LAST:event_btnSalirMouseEntered

    private void btnSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseExited
        this.btnSalir.setBackground(new Color(204,123,133));
    }//GEN-LAST:event_btnSalirMouseExited

    private void btnListaProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaProveedoresMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaProveedoresMouseClicked

    private void btnCrearProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearProveedorMouseClicked
        this.dialogProvider= new  DialogNewProvider(this, true,1);
        this.dialogProvider.setVisible(true);
        //obtengo el Provider
        Provider prov=dialogProvider.getProveedor();
        boolean bandera=false;
         
        if(prov!=null)
            bandera=this.restaurante.getBd().getCrudProvider().createProvider(prov); 
        
        if(bandera){
            this.restaurante.updateDataBase(); 
            JOptionPane.showMessageDialog(this, "Proveedor: "+prov.getName()+" Creado Correctamente"
                    + " 'recargue la lista de Proveedores' ");
        }else{
            JOptionPane.showMessageDialog(this, "NO se ha Creado un Nuevo Proveedor ");
        }
        
          
    }//GEN-LAST:event_btnCrearProveedorMouseClicked

    private void btnCreateSupplyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateSupplyMouseClicked
        
        ArrayList<Category>categories=this.restaurante.getBd().getCrudCategory().getAllCategories();
        System.out.println("Principal "+categories.size());
        DialogSupply dialogSupply= new DialogSupply(this, true,
                1,categories );
        dialogSupply.setVisible(true);
        
        Supply supply=dialogSupply.getSupply();
        boolean bandera=false;
//        System.out.println("El Supply creado en el Dialogo fuée:"+dialogSupply.getSupply().getName()
//                +"Su Categoria"+supply.getCategory().getName()+supply.getCategory().getUnityMeasure());
        if(supply!=null)
            bandera=this.restaurante.getBd().getCrudSupply().cretaSupply(supply); 
        
        if(bandera){
            this.restaurante.updateDataBase(); 
            JOptionPane.showMessageDialog(this, "Insumo: "+supply.getName()+" Creado Correctamente"
                    + " 'recargue la lista Insumos' ");
        }else{
            JOptionPane.showMessageDialog(this, "NO se ha Creado un Nuevo Insumo ");
        }
     
        
    }//GEN-LAST:event_btnCreateSupplyMouseClicked

    private void btnCreateSupplyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateSupplyMouseEntered
        this.btnCreateSupply.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnCreateSupplyMouseEntered

    private void btnCreateSupplyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateSupplyMouseExited
        this.btnCreateSupply.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnCreateSupplyMouseExited

    private void btnCreateSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSupplyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateSupplyActionPerformed

    private void btnListaInsumosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaInsumosMouseClicked

        this.panelInsumos= new PanelInsumos("Lista de Los Insumos", restaurante);
        this.panelInsumos.setSize(860, 460);
//        panelCompras.setLocation(5, 5);
        panelPrincipal.removeAll();
        panelPrincipal.add(panelInsumos);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnListaInsumosMouseClicked

    /**
     * Evento para crear compra.
     * @param evt 
     */
    private void btnCrearComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearComprasMouseClicked
        //Dialogo que permite crear una compra 
        DialogNewPurchase diaPurchase= new DialogNewPurchase(this,true,restaurante);
        diaPurchase.setVisible(true);    
        Purchase purchase= diaPurchase.getPurchase();
        
        if(purchase!=null&&purchase.getProvider()!=null&&purchase.getInsumos().size()>0){
           
           boolean bandera=this.restaurante.addPurchase(purchase);
//           boolean bandera= this.restaurante.getBd().getCrudPurchase().createPurchase(purchase);
           this.restaurante.updateDataBase();
           if(bandera){
               JOptionPane.showMessageDialog(this, "Compra Agregada Con Éxito"+purchase.getInsumos().size());
           }else{
               JOptionPane.showMessageDialog(this, "No se Pudó Agregar La Compra");
           }
        }
        
    }//GEN-LAST:event_btnCrearComprasMouseClicked

    private void btnListaComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaComprasMouseClicked
        panelCompras= new PanelCompras("Lista De Compras",this.restaurante);
        panelCompras.setSize(830, 450);
//        panelCompras.setLocation(5, 5);
        panelPrincipal.removeAll();
        panelPrincipal.add(panelCompras);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnListaComprasMouseClicked

    private void btnCrearSalidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearSalidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearSalidaMouseClicked

    private void btnMenusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenusMouseEntered
        this.btnMenus.setBackground(new Color(0,0,128));
    }//GEN-LAST:event_btnMenusMouseEntered

    private void btnMenusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenusMouseExited
         this.btnMenus.setBackground(new Color(50,113,166));
    }//GEN-LAST:event_btnMenusMouseExited

    private void btnMenusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenusActionPerformed

    private void btnMenusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenusMouseClicked
        panelMenus= new PanelMenus("Lista De Menus del Restaurante",this.restaurante);
        panelMenus.setSize(830, 450);
//        panelCompras.setLocation(5, 5);
        panelPrincipal.removeAll();
        panelPrincipal.add(panelMenus);
        panelPrincipal.revalidate();
        panelPrincipal.repaint();
    }//GEN-LAST:event_btnMenusMouseClicked

    private void btnListaSalidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListaSalidasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnListaSalidasMouseClicked

    /**
     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Principal(null).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjustes;
    private javax.swing.JButton btnCrearCompras;
    private javax.swing.JButton btnCrearProveedor;
    private javax.swing.JButton btnCrearSalida;
    private javax.swing.JButton btnCreateSupply;
    private javax.swing.JButton btnListaCompras;
    private javax.swing.JButton btnListaInsumos;
    private javax.swing.JButton btnListaProveedores;
    private javax.swing.JButton btnListaSalidas;
    private javax.swing.JButton btnListaVentas;
    private javax.swing.JButton btnMenus;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel minim;
    private javax.swing.JPanel panelHead;
    private javax.swing.JPanel panelNav;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel txtFecha;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
